create table
  public.grade (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    student_id bigint not null,
    subject_id bigint not null,
    grade smallint not null,
    constraint grade_pkey primary key (id),
    constraint public_grade_student_id_fkey foreign key (student_id) references student (id) on update cascade on delete cascade,
    constraint public_grade_subject_id_fkey foreign key (subject_id) references subject (id) on update cascade on delete cascade
  ) tablespace pg_default;
