create table
  public.subject (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text not null,
    constraint subject_pkey primary key (id)
  ) tablespace pg_default;
