create table
  public.student (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    age smallint not null,
    gender public.gender not null,
    constraint student_pkey primary key (id)
  ) tablespace pg_default;
